void hello();
double divide(int a, int b);
void functions();
void loops();
void conditions();
void buffer_overflow();
void add(int *x, int add);
void pointers();
void structures();
void strings();
void memory_allocator();
void lb();
